# Generated by Django 5.2.6 on 2025-09-19 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.TextField(blank=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('storage_backend', models.CharField(choices=[('cloudinary', 'Cloudinary'), ('s3', 'Amazon S3'), ('local', 'Local Storage')], default='cloudinary', max_length=20)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('s3_key', models.CharField(blank=True, max_length=500, null=True)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('public_url', models.URLField(max_length=500)),
                ('secure_url', models.URLField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_id', '-created_at'], name='file_upload_request_e25290_idx'), models.Index(fields=['file_type'], name='file_upload_file_ty_314af2_idx'), models.Index(fields=['storage_backend'], name='file_upload_storage_023b46_idx')],
            },
        ),
    ]
